.pragma library
// Settings search index — maps setting cards to tabs for search navigation.
// Each entry: { tabId, cardId, title, description, keywords }
//   tabId    matches an id in SettingsTabs.qml (e.g. "connections", "machine", "about")
//   cardId   matches the objectName on the card Rectangle in the tab QML
//   title / description are translated; keywords are English fallbacks for cross-language search
//
// Tab ordering and localized names are resolved via the SettingsTabs singleton —
// this file does not need to know anything about tab indexes.

function getSearchEntries(tr) {
    // tr = TranslationManager.translate function
    // If not provided, use identity (returns fallback)
    if (!tr) tr = function(key, fallback) { return fallback }

    return [
        // Connections
        { tabId: "connections", cardId: "machineConnection",
          title: tr("settings.bluetooth.machine", "Machine"),
          description: tr("settings.search.machineConnectionDesc", "Connect to DE1 via Bluetooth or USB"),
          keywords: ["ble", "bluetooth", "usb", "pair", "connect", "device", "machine"] },
        { tabId: "connections", cardId: "scaleConnection",
          title: tr("settings.bluetooth.scalesRefractometer", "Scales / Refractometer"),
          description: tr("settings.search.scaleConnectionDesc", "Pair a Bluetooth scale or refractometer"),
          keywords: ["scale", "acaia", "decent", "felicita", "weight", "pair", "tds", "refractometer", "atago"] },

        // Screensaver — auto-sleep and auto-wake also live on the Screensaver tab
        { tabId: "screensaver", cardId: "screensaver",
          title: tr("settings.screensaver.settings", "Screensaver Settings"),
          description: tr("settings.search.screensaverDesc", "Choose screensaver type and settings"),
          keywords: ["screensaver", "attractor", "pipes", "clock", "video", "image", "dim"] },
        { tabId: "screensaver", cardId: "autoSleep",
          title: tr("settings.preferences.autoSleep", "Auto-Sleep"),
          description: tr("settings.preferences.autoSleepDesc", "Put the machine to sleep after inactivity"),
          keywords: ["sleep", "timeout", "power", "idle", "standby"] },
        { tabId: "screensaver", cardId: "screensaverDim",
          title: tr("settings.screensaver.screensaver", "Screensaver"),
          description: tr("settings.search.screensaverDimDesc", "Dim the screen after inactivity"),
          keywords: ["dim", "brightness", "screensaver", "display", "darkness"] },
        { tabId: "screensaver", cardId: "autoWake",
          title: tr("settings.options.autoWake", "Auto-Wake Timer"),
          description: tr("settings.search.autoWakeDesc", "Schedule automatic wake-up times"),
          keywords: ["wake", "schedule", "alarm", "morning", "timer", "power"] },

        // Machine
        { tabId: "machine", cardId: "batteryCharging",
          title: tr("settings.preferences.batteryCharging", "Battery Charging"),
          description: tr("settings.search.batteryDesc", "Smart charging mode for battery health"),
          keywords: ["battery", "charge", "usb", "power", "smart charging"] },
        { tabId: "machine", cardId: "shotMap",
          title: tr("settings.shotmap.title", "Shot Map"),
          description: tr("settings.shotmap.description", "Share your shots on the global map at decenza.coffee"),
          keywords: ["map", "location", "gps", "share", "global"] },
        { tabId: "machine", cardId: "maintenance",
          title: tr("settings.maintenance.title", "Maintenance"),
          description: tr("settings.maintenance.description", "Keep your machine clean and ready for storage."),
          keywords: ["maintenance", "descale", "descaling", "transport", "drain", "air purge", "clean", "storage", "travel", "vacation", "empty", "water"] },
        { tabId: "machine", cardId: "themeMode",
          title: tr("settings.preferences.themeMode", "Theme Mode"),
          description: tr("settings.search.themeModeDesc", "Dark mode, light mode, follow system"),
          keywords: ["dark", "light", "theme", "mode", "appearance", "system"] },
        { tabId: "machine", cardId: "themeMode",
          title: tr("settings.preferences.background", "Background"),
          description: tr("settings.search.backgroundDesc", "Choose a background image for the idle screen and other pages"),
          keywords: ["background", "wallpaper", "image", "photo", "screensaver", "idle"] },
        { tabId: "machine", cardId: "extractionView",
          title: tr("settings.preferences.extractionView", "Extraction View"),
          description: tr("settings.preferences.extractionViewDesc", "Visualization during espresso extraction"),
          keywords: ["chart", "cup", "graph", "extraction", "view"] },
        { tabId: "machine", cardId: "shotReviewTimer",
          title: tr("settings.machine.shotReviewTimer", "Shot Review Timer"),
          description: tr("settings.machine.shotReviewTimerDesc", "Return to idle after reviewing shot"),
          keywords: ["review", "post-shot", "timeout", "close", "auto"] },
        { tabId: "machine", cardId: "shotReviewTimer",
          title: tr("settings.visualizer.editAfterShot", "Edit After Shot"),
          description: tr("settings.machine.editAfterShotDesc", "Open shot review page after each extraction"),
          keywords: ["review", "post-shot", "edit", "shot info", "after"] },
        { tabId: "machine", cardId: "shotReviewTimer",
          title: tr("settings.visualizer.clearNotesOnStart", "Clear Notes on Start"),
          description: tr("settings.visualizer.clearNotesOnStartDesc", "Clear shot notes when starting a new shot"),
          keywords: ["notes", "clear", "reset", "start"] },
        { tabId: "machine", cardId: "screenZoom",
          title: tr("settings.machine.screenZoom", "Screen Zoom"),
          description: tr("settings.machine.screenZoomDesc", "Adjust UI scale individually for each screen to optimize readability."),
          keywords: ["zoom", "scale", "size", "ui", "display", "dpi"] },
        { tabId: "machine", cardId: "launcherMode",
          title: tr("settings.options.launcherMode", "Launcher Mode"),
          description: tr("settings.options.launcherModeDesc", "Set Decenza as the Android home screen. Press Home to return here instead of the default launcher."),
          keywords: ["launcher", "home", "android", "kiosk"] },
        { tabId: "machine", cardId: "waterLevel",
          title: tr("settings.options.waterLevel", "Water Level"),
          description: tr("settings.search.waterLevelDesc", "Water tank level and refill threshold"),
          keywords: ["water", "tank", "level", "refill"] },
        { tabId: "machine", cardId: "waterRefillThreshold",
          title: tr("settings.options.waterRefillLevel", "Water Refill Threshold"),
          description: tr("settings.options.waterRefillLevelDesc", "Water level at which the machine warns you to refill"),
          keywords: ["water", "refill", "threshold", "warning"] },
        { tabId: "machine", cardId: "refillKit",
          title: tr("settings.preferences.refillKit", "Refill Kit"),
          description: tr("settings.preferences.refillKitDesc", "Control whether the machine uses an automatic water refill kit"),
          keywords: ["refill", "kit", "plumb", "water", "auto"] },
        { tabId: "machine", cardId: "steamHeater",
          title: tr("settings.preferences.steamHeater", "Steam Heater"),
          description: tr("settings.preferences.steamHeaterDesc", "Pre-heat for faster steaming"),
          keywords: ["steam", "heater", "flush", "auto", "temperature", "two-tap", "two tap", "purge", "stop", "headless"] },
        { tabId: "machine", cardId: "simulationMode",
          title: tr("settings.machine.simulationModeTitle", "Simulation Mode"),
          description: tr("settings.machine.simulationModeDesc", "Use the app without a connected DE1 machine"),
          keywords: ["offline", "simulation", "demo", "unlock", "gui", "disconnect"] },
        { tabId: "machine", cardId: "pocketIntegration",
          title: tr("settings.machine.pocketIntegrationTitle", "Pocket Integration"),
          description: tr("settings.machine.pocketIntegrationDesc", "Allow the Pocket app to view and control your screen remotely. Requires an active Pocket pairing."),
          keywords: ["pocket", "remote", "pair", "control", "screen"] },
        { tabId: "machine", cardId: "temperatureUnit",
          title: tr("settings.options.temperatureUnit", "Temperature unit"),
          description: tr("settings.search.temperatureUnitDesc", "Show temperatures in Celsius or Fahrenheit"),
          keywords: ["fahrenheit", "celsius", "units", "°f", "°c", "degrees", "temperature"] },

        // External: Auto-Load Profile lives on ProfileSelectorPage (not a
        // settings tab). When chosen, the dialog navigates there.
        { externalRoute: "profileSelector",
          title: tr("settings.search.autoLoadProfileTitle", "Auto-Load Profile"),
          description: tr("settings.search.autoLoadProfileDesc", "Pin a profile to auto-load on app start, wake, or after idle"),
          keywords: ["auto-load", "auto load", "automatic profile", "pin", "default", "revert", "home"] },

        // Calibration
        { tabId: "calibration", cardId: "flowCalibration",
          title: tr("settings.preferences.flowCalibration", "Flow Calibration"),
          description: tr("settings.search.flowCalDesc", "Calibrate flow sensor accuracy"),
          keywords: ["flow", "calibration", "sensor", "auto", "multiplier"] },
        { tabId: "calibration", cardId: "weightStopTiming",
          title: tr("settings.calibration.weightStopTiming", "Weight Stop Timing"),
          description: tr("settings.search.weightStopDesc", "Auto-learned stop-at-weight lag timing"),
          keywords: ["weight", "stop", "saw", "lag", "timing", "scale"] },
        { tabId: "calibration", cardId: "heaterCalibration",
          title: tr("settings.calibration.title", "Heater Calibration"),
          description: tr("settings.search.heaterCalDesc", "Idle temp, warmup flow rates, timeout"),
          keywords: ["heater", "temperature", "warmup", "calibrate", "idle"] },
        { tabId: "calibration", cardId: "virtualScale",
          title: tr("settings.preferences.virtualScale", "Virtual Scale"),
          description: tr("settings.search.virtualScaleDesc", "Estimate weight from flow sensor"),
          keywords: ["virtual", "scale", "flow", "weight", "estimate", "fallback"] },
        { tabId: "calibration", cardId: "preferWeight",
          title: tr("settings.calibration.preferWeightOverVolume", "Prefer Weight over Volume"),
          description: tr("settings.search.preferWeightDesc", "Ignore volume limit when scale is paired"),
          keywords: ["weight", "volume", "sav", "ignore", "scale", "stop"] },
        { tabId: "calibration", cardId: "sensorCalibration",
          title: tr("settings.sensorCalibration.title", "Sensor Calibration"),
          description: tr("settings.sensorCalibration.description", "Correct what the machine reads against an external gauge or thermometer"),
          keywords: ["sensor", "pressure", "temperature", "thermometer", "gauge", "offset", "calibrate", "accuracy"] },
        { tabId: "calibration", cardId: "steamHealth",
          title: tr("settings.calibration.steamHealth", "Steam Health"),
          description: tr("settings.search.steamHealthDesc", "Steam pressure and temperature drift from your clean-machine baseline"),
          keywords: ["steam", "health", "descale", "clean", "milk", "residue", "scale", "buildup", "drift", "baseline", "wand"] },

        // History & Data
        { tabId: "historyData", cardId: "shotHistory",
          title: tr("settings.search.shotHistoryTitle", "Shot History"),
          description: tr("settings.search.shotHistoryDesc", "View and manage shot history"),
          keywords: ["history", "shots", "past", "records"] },
        { tabId: "historyData", cardId: "shotHistory",
          title: tr("settings.history.importFromDE1", "Import from DE1 App"),
          description: tr("settings.search.importDE1Desc", "Import shot history from DE1 tablet app"),
          keywords: ["import", "de1", "migrate", "transfer"] },
        { tabId: "historyData", cardId: "dailyBackup",
          title: tr("settings.data.dailybackup", "Daily Backup"),
          description: tr("settings.search.dailyBackupDesc", "Auto-backup shots, settings, profiles daily"),
          keywords: ["backup", "restore", "save", "data", "auto"] },
        { tabId: "historyData", cardId: "enableServer",
          title: tr("settings.history.enableserver", "Enable Server"),
          description: tr("settings.data.enableserverdesc", "Access shot data, layout editor, and AI from your browser"),
          keywords: ["server", "http", "web", "remote", "network", "share"] },
        { tabId: "historyData", cardId: "enableServer",
          title: tr("settings.data.enablesecurity", "Enable Security"),
          description: tr("settings.data.enablesecuritydesc", "Encrypt connections and require a code from your authenticator app"),
          keywords: ["security", "https", "totp", "authenticator", "password", "encryption"] },
        { tabId: "historyData", cardId: "shotHistory",
          title: tr("settings.data.importfrom", "Import from Another Device"),
          description: tr("settings.search.deviceMigrationDesc", "Import from another Decenza device on WiFi"),
          keywords: ["migration", "transfer", "device", "import", "wifi", "sync"] },
        { tabId: "historyData", cardId: "enableServer",
          title: tr("settings.search.factoryResetTitle", "Factory Reset"),
          description: tr("settings.search.factoryResetDesc", "Remove all data and uninstall"),
          keywords: ["reset", "factory", "delete", "clear", "uninstall", "wipe"] },
        { tabId: "historyData", cardId: "exportShotsCard",
          title: tr("settings.data.exportshots", "Export Shots to File"),
          description: tr("settings.search.exportShotsDesc", "Mirror shots to JSON files for external tools"),
          keywords: ["export", "json", "shots", "mirror", "backup", "files"] },

        // Themes
        { tabId: "themes", cardId: "themeColors",
          title: tr("settings.search.themeColorsTitle", "Theme Colors"),
          description: tr("settings.search.themeColorsDesc", "Customize app color palette"),
          keywords: ["color", "theme", "palette", "customize", "dark", "light"] },
        { tabId: "themes", cardId: "saveTheme",
          title: tr("settings.search.saveThemeTitle", "Save Theme"),
          description: tr("settings.search.saveThemeDesc", "Save current color scheme as named theme"),
          keywords: ["save", "theme", "preset", "custom"] },

        // Layout
        { tabId: "layout", cardId: "layoutEditor",
          title: tr("settings.layout.title", "Home Screen Layout"),
          description: tr("settings.search.layoutDesc", "Customize idle screen widgets and zones"),
          keywords: ["layout", "widget", "zone", "customize", "idle", "home", "editor"] },

        // Shot Upload
        { tabId: "visualizer", cardId: "visualizer",
          title: tr("settings.upload.visualizerTitle", "Visualizer"),
          description: tr("settings.search.visualizerDesc", "Connect to visualizer.coffee for shot sharing"),
          keywords: ["visualizer", "coffee", "upload", "share", "account"] },
        { tabId: "visualizer", cardId: "decentAccount",
          title: tr("decent.account.title", "Decent Account"),
          description: tr("decent.account.desc", "Upload your shots to your account at decentespresso.com"),
          keywords: ["decent", "decentespresso", "account", "upload", "shots", "login"] },
        { tabId: "visualizer", cardId: "uploadSettings",
          title: tr("settings.upload.settingsTitle", "Upload Settings"),
          description: tr("settings.upload.settingsDesc", "When shots are uploaded, for every destination that is switched on"),
          keywords: ["upload", "auto", "automatic", "update", "minimum", "duration"] },

        // AI
        { tabId: "ai", cardId: "aiProvider",
          title: tr("settings.ai.section.provider", "AI Provider"),
          description: tr("settings.search.aiProviderDesc", "Configure AI for shot analysis"),
          keywords: ["ai", "openai", "anthropic", "gemini", "ollama", "api", "key", "model"] },
        { tabId: "ai", cardId: "mcpServer",
          title: tr("settings.ai.mcp.enable", "Enable MCP Server"),
          description: tr("settings.search.mcpDesc", "Model Context Protocol server for Claude"),
          keywords: ["mcp", "claude", "server", "protocol", "discuss"] },

        // MQTT
        { tabId: "mqtt", cardId: "mqtt",
          title: tr("mqtt.title", "MQTT"),
          description: tr("settings.search.mqttDesc", "Home automation broker connection"),
          keywords: ["mqtt", "home", "assistant", "automation", "broker", "ha"] },

        // Language & Access
        { tabId: "languageAccess", cardId: "language",
          title: tr("language.languages", "Languages"),
          description: tr("settings.search.languageDesc", "Select app language"),
          keywords: ["language", "translate", "locale", "i18n"] },
        { tabId: "languageAccess", cardId: "accessibility",
          title: tr("settings.accessibility.title", "Accessibility"),
          description: tr("settings.accessibility.desc", "Screen reader support and audio feedback for blind and visually impaired users"),
          keywords: ["accessibility", "talkback", "voiceover", "screen reader", "tts", "blind"] },
        { tabId: "languageAccess", cardId: "accessibility",
          title: tr("settings.accessibility.voiceAnnouncements", "Voice Announcements"),
          description: tr("settings.accessibility.voiceAnnouncementsDesc", "Speak shot progress aloud"),
          keywords: ["voice", "speech", "tts", "announce", "talk"] },
        { tabId: "languageAccess", cardId: "accessibility",
          title: tr("settings.accessibility.frameTick", "Frame Tick Sound"),
          description: tr("settings.accessibility.frameTickDesc", "Play a tick when the machine moves to the next extraction step"),
          keywords: ["tick", "sound", "audio", "frame", "beep"] },

        // About
        { tabId: "about", cardId: "checkUpdates",
          title: tr("settings.update.currentversion", "Current Version"),
          description: tr("settings.search.checkUpdatesDesc", "Auto-check and download app updates"),
          keywords: ["update", "version", "download", "beta", "release"] },
        { tabId: "about", cardId: "firmwareUpdate",
          title: tr("firmware.card.title", "DE1 Firmware"),
          description: tr("settings.search.firmwareDesc", "Check, update, or downgrade the DE1 machine firmware"),
          keywords: ["firmware", "de1", "update", "downgrade", "nightly", "stable", "flash", "serial", "serial number"] },
        { tabId: "about", cardId: "releaseNotes",
          title: tr("settings.search.releaseNotesTitle", "Release Notes"),
          description: tr("settings.search.releaseNotesDesc", "What's new in this version"),
          keywords: ["release", "notes", "changelog", "new", "version"] },
        { tabId: "about", cardId: "checkUpdates",
          title: tr("about.supportProject", "Support This Project"),
          description: tr("settings.search.donateDesc", "Support Decenza development via PayPal"),
          keywords: ["donate", "paypal", "support", "money", "tip"] },
    ]
}
